### ISSUE TITLE
Adding abc.abstractmethod to an abstractcp.Abstract class

### ISSUE THREAD

**Issue by alijewers** [reinhrst/abstractcp#1]
Hi there,

Is it possible to have a class which derives from both `abstractcp.Abstract` and the builtin `abc.ABC`? I would like to be able to define a base class which has both abstract class properties AND abstract methods that subclasses must override. Right now doing something along the lines of:

```python
from abc import ABC, abstractmethod
from abstractcp import Abstract, abstract_class_property

class BaseClass(ABC, Abstract):
    foo = abstract_class_property(str)

    @abstractmethod
    def bar(self):
        pass

class SubClass(BaseClass):
    foo = "string"
    
    def bar(self):
        print("In bar")
```

causes an error on startup:

```
.../python3.8/site-packages/abstractcp/__init__.py:98: in __init_subclass__
    if isinstance(getattr(cls, name), _AbstractClassProperty):
E   AttributeError: __abstractmethods__
```

and removing `ABC` means an exception is no longer raised if the subclass does not implement the abstract method.

Any help would be appreciated, thanks!

**Comment by reinhrst** [comment]
Interesting. Shouldn't be too hard, I will take a look later today!

**Comment by alijewers** [comment]
Thanks, appreciate it!

**Comment by reinhrst** [comment]
Hmmmm, I don't think I intended to close it just yet. Still experimenting a bit -- should have made this a pull request for myself and see tests :). Anyways, it fixes the issue for me on 3.9.1 -- I should see the tox tests running, and figure out again how to upload to pypi, and I'll release a new version :)

**Comment by reinhrst** [comment]
Ok, version 0.9.7 is on pypi now, fixes this issue. Issue added to unit tests as well. Let me know if you encounter any other issues!

**Comment by alijewers** [comment]
Awesome, that was rapid, I'll give it a go. Thanks!

**Comment by alijewers** [comment]
Had a go with 0.9.7, and found I was still getting the same error unfortunately, but it had shifted to a new point in the code.

I've opened a PR ( #2 ) with a fix & a few extra lines of testing, let me know what you think!

**Comment by alijewers** [comment]
(@reinhrst ) - please excuse the ping, I don't know if you get notifications for issues which are already closed
